# Generated by Django 4.2.7 on 2023-12-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
