# Generated by Django 4.2.7 on 2023-12-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_customuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
    ]
