# Generated by Django 4.2.7 on 2023-12-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_modeladress_address2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelAdress',
            new_name='ModelAdressModal',
        ),
    ]
