# Generated by Django 4.2.7 on 2024-01-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_modeladress_modeladressmodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(default=45),
            preserve_default=False,
        ),
    ]
