# Generated by Django 4.2.7 on 2024-01-09 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_category_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('locality', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('N', 'Narowal'), ('D', 'Doday wali'), ('R', 'Ran'), ('C', 'Chaly wali'), ('R', 'Ransinwal'), ('K', 'Kharal'), ('Cl', 'Class goraya'), ('Ja', 'Jajo wali'), ('M', 'Mandra wala')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
