# Generated by Django 4.2.7 on 2024-01-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_customer_city_alter_customer_locality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='Name',
        ),
    ]
