# Generated by Django 4.2.7 on 2024-01-11 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_name_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_orderplaced', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
